@startuml
autonumber

React_Client -> Firebase: Authentication Request
Firebase --> React_Client: Authentication Response

React_Client -> Node_Backend: User Request with AuthenticationToken
Node_Backend -> Firebase: GetUser with AuthenticationToken
Firebase --> Node_Backend: Response with User Details
database Database_Mongo as db
Node_Backend -> db: Request Data (Mongoose)
db --> Node_Backend: Response Data
Node_Backend --> React_Client: Response Data

@enduml